# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels:
      - "version-upgrade"
      - "maven"
    pull-request-branch-name:
      separator: "_"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "version-upgrade"
      - "actions"
    pull-request-branch-name:
      separator: "_"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/web" # Location of package manifests
    labels:
      - "version-upgrade"
      - "npm"
    pull-request-branch-name:
      separator: "_"
    schedule:
      interval: "daily"
