version: '3'



services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: fullstackdemo
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=password
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/db
    depends_on:
      - database

  database:
    image: postgres:14.7
    hostname: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - ALLOW_IP_RANGE='0.0.0.0/0'
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

