version: '3'

tasks:
  dev-dependencies:
    cmd: docker compose up -d database

  build-all:
    cmds:
      - task: build-openapi
      - task: web-build
      - mvn package -Pprod

  build-fast:
    cmd: mvn package -Pprod -DskipTests -DskipChecks

  build:
    cmd: mvn package -Pprod

  build-openapi:
    cmd: mvn package -Popen-api -DskipTests -DskipChecks -am -pl "service"

  run:
    cmd: docker compose up -d service --build

  dev:
    cmds:
      - task: dev-dependencies
      - mvn compile quarkus:dev -am -pl "service"

  clean:
    cmd: mvn clean

  web-build:
    cmd: mvn clean package -pl web -DskipTests

  dev-web:
    cmd: yarn --cwd ./web dev

  generate-jwt:
    cmd: mvn exec:java -pl "service" -Dexec.mainClass=com.lopixlabs.app.fullstackdemo.GenerateToken -Dexec.classpathScope=test -Dsmallrye.jwt.sign.key.location=privateKey.pem
